remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Hardest Lists List
description: List of the Hardest Lists in Geometry Dash.
